/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compile.provider;

public class LibraryForCompile {
    public boolean someLibraryMethod() {
        return true;
    }
    public boolean newMethod() {return true;}
}
