/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package consumer;

import compile.provider.LibraryForCompile;
import impl.provider.LibraryForImpl;

public class ConsumerLibrary {
    private LibraryForCompile compileLib;
    private LibraryForImpl implLib;
}
