/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package impl.provider;

public class LibraryForImpl {
    public boolean someLibraryMethod() {
        return true;
    }
    public boolean newMethod3() {return true;}
}
